### ISSUE TITLE
Can a site manager promote a user to administrator?

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-custom-functionality#7]
Need to know if it's possible for a UCSC site manager to promote a user to _administrator_.

**Comment by Herm71** [comment]
The answer is: Yes.

**Comment by Herm71** [comment]
@knice, this [Stack Exchange function](https://wordpress.stackexchange.com/questions/43260/prevent-or-disable-creating-new-users-or-changing-roles-of-existing-users-to-adm) will hide the "Administrator" role from the "UCSC Site Manager" role. No other roles provide access to the "Users" admin area. The Stack Exchange function also removes the "Editor" and "Author" roles but I removed that portion of the code so those roles are untouched in ours. 

The shot below is what an Admin user will see:
![admin-user](https://user-images.githubusercontent.com/1000543/183760923-08bafba0-af01-4e1a-a4e3-3cb205f25de2.png)

The shot below is what the UCSC Site Manager will see:
![site-manager](https://user-images.githubusercontent.com/1000543/183761056-657a4a03-0a35-442e-9c9e-4e81080fe831.png)
